MVC_Practica01NETCore/MVC_Practica01NETCore/Controllers/PersonasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.RegularExpressions;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MVC_Practica01NETCore.Models;

namespace MVC_Practica01NETCore.Controllers
{
    public class PersonasController : Controller
    {
        private readonly Practica1Ds2Context _context;

        public PersonasController(Practica1Ds2Context context)
        {
            _context = context;
        }

        // GET: Personas
        public async Task<IActionResult> Index()
        {
            var personas = await _context.Personas.ToListAsync();
            return View(personas);
        }

        // GET: Personas/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Personas/Create     
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Nombre,Apellido,TipoDocumento,Dni,CarnetExtranjero,Pasaporte,FechaNacimiento")] Persona persona)
        {
            if (ModelState.IsValid)
            {
                // Validar la edad, debe ser mayor o igual a 18 años
                if (CalcularEdad(persona.FechaNacimiento) >= 18)
                {
                    // Validar el nombre
                    if (!ValidarNombre(persona.Nombre))
                    {
                        ModelState.AddModelError("Nombre", "Formato de nombre incorrecto.");
                        return View(persona);
                    }

                    // Validar el apellido
                    if (!ValidarApellido(persona.Apellido))
                    {
                        ModelState.AddModelError("Apellido", "Formato de apellido incorrecto.");
                        return View(persona);
                    }

                    // Validar el documento
                    if (persona.TipoDocumento == "DNI" && !ValidarDocumento("DNI", persona.Dni))
                    {
                        ModelState.AddModelError("Dni", "Formato de DNI incorrecto.");
                        return View(persona);
                    }
                    else if (persona.TipoDocumento == "Pasaporte" && !ValidarDocumento("Pasaporte", persona.Pasaporte))
                    {
                        ModelState.AddModelError("Pasaporte", "Formato de pasaporte incorrecto.");
                        return View(persona);
                    }
                    else if (persona.TipoDocumento == "CarnetExtranjero" && !ValidarDocumento("CarnetExtranjero", persona.CarnetExtranjero))
                    {
                        ModelState.AddModelError("CarnetExtranjero", "Formato de Carnet Extranjero incorrecto.");
                        return View(persona);
                    }

                    // Verificar si el documento ya existe en la base de datos
                    bool documentoExistente = await VerificarDocumentoExistente(persona);

                    if (documentoExistente)
                    {
                        switch (persona.TipoDocumento)
                        {
                            case "DNI":
                                ModelState.AddModelError("Dni", "El DNI ya existe en la base de datos.");
                                break;
                            case "Pasaporte":
                                ModelState.AddModelError("Pasaporte", "El Pasaporte ya existe en la base de datos.");
                                break;
                            case "CarnetExtranjero":
                                ModelState.AddModelError("CarnetExtranjero", "El Carnet Extranjero ya existe en la base de datos.");
                                break;
                        }
                        return View(persona);
                    }

                    _context.Add(persona);
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    ModelState.AddModelError("FechaNacimiento", "La persona debe ser mayor de 18 años para registrarse.");
                }
            }

            return View(persona);
        }


        // GET: Personas/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var persona = await _context.Personas.FindAsync(id);
            if (persona == null)
            {
                return NotFound();
            }

            return View(persona);
        }

        // POST: Personas/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("Id,Nombre,Apellido,TipoDocumento,Dni,CarnetExtranjero,Pasaporte,FechaNacimiento")] Persona persona)
        {
            if (id != persona.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                if (CalcularEdad(persona.FechaNacimiento) >= 18)
                {
                    // Validar el nombre
                    if (!ValidarNombre(persona.Nombre))
                    {
                        ModelState.AddModelError("Nombre", "Formato de nombre incorrecto.");
                        return View(persona);
                    }

                    // Validar el apellido
                    if (!ValidarApellido(persona.Apellido))
                    {
                        ModelState.AddModelError("Apellido", "Formato de apellido incorrecto.");
                        return View(persona);
                    }

                    // Verificar si el número de documento ha cambiado y si es válido
                    var personaOriginal = await _context.Personas.FirstOrDefaultAsync(p => p.Id == id);
                    if (personaOriginal == null)
                    {
                        return NotFound();
                    }

                    if (persona.TipoDocumento == "DNI" && persona.Dni != personaOriginal.Dni)
                    {
                        if (!ValidarDocumento(persona.TipoDocumento, persona.Dni))
                        {
                            ModelState.AddModelError("Dni", "Formato de DNI incorrecto.");
                            return View(persona);
                        }

                        bool documentoExistente = await VerificarDocumentoExistente(persona);
                        if (documentoExistente)
                        {
                            ModelState.AddModelError("Dni", "El nuevo DNI ya existe en la base de datos.");
                            return View(persona);
                        }
                    }
                    else if (persona.TipoDocumento == "Pasaporte" && persona.Pasaporte != personaOriginal.Pasaporte)
                    {
                        if (!ValidarDocumento(persona.TipoDocumento, persona.Pasaporte))
                        {
                            ModelState.AddModelError("Pasaporte", "Formato de pasaporte incorrecto.");
                            return View(persona);
                        }

                        bool documentoExistente = await VerificarDocumentoExistente(persona);
                        if (documentoExistente)
                        {
                            ModelState.AddModelError("Pasaporte", "El nuevo Pasaporte ya existe en la base de datos.");
                            return View(persona);
                        }
                    }
                    else if (persona.TipoDocumento == "CarnetExtranjero" && persona.CarnetExtranjero != personaOriginal.CarnetExtranjero)
                    {
                        if (!ValidarDocumento(persona.TipoDocumento, persona.CarnetExtranjero))
                        {
                            ModelState.AddModelError("CarnetExtranjero", "Formato de Carnet Extranjero incorrecto.");
                            return View(persona);
                        }

                        bool documentoExistente = await VerificarDocumentoExistente(persona);
                        if (documentoExistente)
                        {
                            ModelState.AddModelError("CarnetExtranjero", "El nuevo Carnet Extranjero ya existe en la base de datos.");
                            return View(persona);
                        }
                    }

                    // Actualizar todos los campos de la entidad original con los valores del modelo persona
                    _context.Entry(personaOriginal).CurrentValues.SetValues(persona);

                    try
                    {
                        await _context.SaveChangesAsync();
                        return RedirectToAction(nameof(Index));
                    }
                    catch (DbUpdateConcurrencyException)
                    {
                        if (!PersonaExists(persona.Id))
                        {
                            return NotFound();
                        }
                        else
                        {
                            throw;
                        }
                    }
                }
                else
                {
                    ModelState.AddModelError(string.Empty, "La persona debe ser mayor de 18 años para editar sus datos.");
                }
            }

            return View(persona);
        }



        // GET: Personas/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var persona = await _context.Personas
                .FirstOrDefaultAsync(m => m.Id == id);
            if (persona == null)
            {
                return NotFound();
            }

            return View(persona);
        }

MVC_Practica01NETCore/MVC_Practica01NETCore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MVC_Practica01NETCore</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MVC_Practica01NETCore.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MVC_Practica01NETCore</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Inicio</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Privacy">Privacidad</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Personas" asp-action="Index">CRUD Personas</a>
                        </li>

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - MVC_Practica01NETCore - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>